# Generated by Django 5.2.6 on 2025-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a profile image (will be stored in MEDIA_ROOT/team/)', null=True, upload_to='team/'),
        ),
    ]
